name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: https://opensource.appworld.in
repository: https://github.com/debojyoti452/dart_standard_lib.git

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  dart_std:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
