name: dart_std
description: A library with full of interactive features that can be used as extension methods.
version: 0.0.7
homepage: https://opensource.appworld.in
repository: https://github.com/debojyoti452/dart_standard_lib.git

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  characters: ^1.3.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  analyzer: ^6.3.0

flutter:
